### ISSUE TITLE
drepfest update 16-10-2024

### ISSUE THREAD

**Issue by KINGhost420** [ergdevops/vendor_xiaomi_raphael-derpfest#1]
I download the rom and not a single game working on mobile data. Done everything but no help
Buy if I connect to wifi games working fine and if I switch to mobile data it's not working 
And battery drain is too high 
And sudden reboot and system crash are happening 

Plz consider the mobile data problem with game ASAP I love this rom so plx fix this issue 
And I downloaded the rom fron official website

**Comment by ergdevops** [comment]
have a look : https://t.me/ergdevchannel/753
